### ISSUE TITLE
I am making a senior project

### ISSUE THREAD

**Issue by laugwang** [ArcaDone/UnityMotorbikeController#1]
I have many quations on this，example I want to change the motorcycle and  like the motorcycle function inside, how to modify?

**Comment by ArcaDone** [comment]
Hi Laugwang. Changing the bike is quite simple because you just assign it where my red bike is. Speaking of "how motorcycles work" you can edit the script however you like. Do you have any specific questions for me?

**Comment by laugwang** [comment]
I'm from Taiwan and then  I maybe have many faulty wording.I know what you mean. but I will use scootor model not motorcycle model. They're not the same structure. So I assign locomotive parts where your red bike and then the physics are very strange.Do the parts vary from model to model?
